#!/bin/bash

# too slow. Postpone to use this feature.
exit 0

# "cd doc" and exit if it fails.
cd doc
if [ $? != 0 ] ; then
    echo "'doc' folder was not found."
    exit 1
fi

# Check updated source file.
updated_file=0
for source_file in $( find ../early_go/src/ ); do
    if [ $source_file -nt html.zip ] ; then
        (( updated_file++ ))
    fi
done

if [ $updated_file -eq 0 ] ; then
    exit 0
fi

# Update documents.
rm -rf ./*
cd ../early_go/tools
../../packages/Doxygen*/tools/doxygen.exe Doxyfile

# Zip documents.
cd ../..
powershell -Command "Compress-Archive -Path doc/html/* -DestinationPath doc/html.zip"

git add doc/html.zip
